### ISSUE TITLE
Html file?

### ISSUE THREAD

**Issue by ratnanil** [Lianikus/cma_week2#1]
I see there is no 'html' file in your repo. In case you are working with Rmarkdown, creating an html file is very simple. Simpliy 'render' the document using the 'Render' Button or the keyboard shortcut <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd>\n\n PS: This issue was generated automatically.

**Comment by Lianikus** [comment]
Hi Nils, thanks for the info! I was actually not working with Rmd in this exercise, but it's good to know for another time.
